# Generated by Django 2.1.5 on 2019-12-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='job',
            name='image2',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='image3',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
    ]
